# Generated by Django 5.0.3 on 2024-04-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('daysWeekOpen', models.CharField(max_length=150)),
                ('openHour', models.CharField(max_length=5)),
                ('closeHour', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=8)),
                ('address', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('cityState', models.CharField(max_length=50)),
            ],
        ),
    ]
