# Generated by Django 5.0.3 on 2024-04-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('role', models.CharField(max_length=30)),
                ('accessLevel', models.CharField(choices=[('1', 'Gerente'), ('2', 'Funcionario')], default=2, max_length=8)),
                ('password', models.CharField(max_length=200)),
                ('service', models.ManyToManyField(blank=True, to='manage_service.service')),
            ],
        ),
    ]
