# Generated by Django 5.0.3 on 2024-04-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='accessLevel',
            field=models.CharField(choices=[('1', 'Gerente'), ('2', 'Funcionario')], default=2, max_length=8),
        ),
    ]
