# Generated by Django 5.0.3 on 2024-04-26 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_customer', '0001_initial'),
        ('manage_employee', '0001_initial'),
        ('manage_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdScheduleDate', models.DateTimeField(auto_now_add=True)),
                ('scheduleDate', models.DateTimeField()),
                ('scheduleHour', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'Concluído'), ('3', 'Cancelado')], default=1, max_length=9)),
                ('observation', models.CharField(max_length=200)),
                ('cancellationReason', models.CharField(max_length=200)),
                ('whoCanceled', models.CharField(choices=[('1', 'Cliente'), ('2', 'Funcionário')], default=1, max_length=11)),
                ('idCustomer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_customer.customer')),
                ('idEmployee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_employee.employee')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_service.service')),
            ],
        ),
    ]
