# Generated by Django 5.0.3 on 2024-05-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='createdScheduleDate',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='cancellationReason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='observation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduleDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='whoCanceled',
            field=models.CharField(blank=True, choices=[('1', 'Cliente'), ('2', 'Funcionário')], default=1, max_length=11),
        ),
    ]
